### ISSUE TITLE
Move dev-db/redis to ::net

### ISSUE THREAD

**Issue by tgurr** [CleverCloud/CleverCloud-exheres#10]
Could you please move redis to `::net`? It would be nice to have it in an official repository, this way we could make use of GitLab/CI and there are also already packages in `::net` which depend on redis, e.g. `net-analyzer/openvas-scanner`. Thanks!

**Comment by Keruspe** [comment]
We already can use the gitlab-ci if you submit changes using gitlab and not github

**Comment by tgurr** [comment]
I did not find anything regarding clevercloud on gitlab.exherbo.org. However it'd be nice to move redis nontheless.

**Comment by Keruspe** [comment]
https://gitlab.exherbo.org/exherbo-unofficial

**Comment by tgurr** [comment]
Thanks for the hint, is it a limitation of GitLab somehow that it doesn't appear when trying to seach for them via the Projects search field or can it be configured to also show up there as well?

**Comment by Keruspe** [comment]
Dunno, will check.

Done btw
